apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: rockodilu/fastapi:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          tcpSocket:
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          tcpSocket:
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    kubernetes.io/spec.ingressClassName: "nginx"
spec:
  tls:
    - hosts:
        - example.com
      secretName: testsecret-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /terms
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000
      - path: /definitions
        pathType: Prefix
        backend:
          service:
            name: fastapi-service
            port:
              number: 8000        
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

... 
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
