apiVersion: v1
kind: Config
clusters:
- cluster:
    server: {{CLUSTER_SERVER_URL}}
    certificate-authority-data: {{CLUSTER_CA_DATA}}
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
users:
- name: my-user
  user:
    token: {{USER_TOKEN}}