apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: rockodilu/fastapi:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          tcpSocket:
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          tcpSocket:
            port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
