name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t fastapi .
      - name: Save Docker image
        run: docker save fastapi | gzip > fastapi.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: fastapi
          path: fastapi.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: fastapi
      - name: Load Docker image
        run: docker run -p 8000:8000 fastapi
      # - name: Install dependencies
      #   run: echo "installing dependencies ..."
      # - name: sudo apt-get install libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev
      #   run: sudo apt-get install libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev -y
      # - name: pip install setuptools wheel
      #   run: pip install setuptools wheel
      # - name: pip install --upgrade pip
      #   run: pip install --upgrade pip
      # - name: pip install pytest
      #   run: pip install pytest
      # - name: Run tests
      #   run: pytest tests/test_loading.py
      - name: Check running containers
        run: curl -v http://0.0.0.0:8000/docs

  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: fastapi
      - name: Load Docker image
        run: docker load < fastapi.tar.gz
