stages:
  - build
  - deploy

variables:
  UVICORN_HOST: "0.0.0.0"
  UVICORN_PORT: "8000"

jobs:
  build:
    stage: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t fastapi .

      - name: Save Docker image
        run: docker save fastapi | gzip > fastapi.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: fastapi
          path: fastapi.tar.gz

  deploy:
    stage: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: fastapi
          path: .

      - name: Load Docker image
        run: docker load < fastapi.tar.gz

      - name: Deploy to Kubernetes
        run: |
          echo "UVICORN_HOST=$UVICORN_HOST" > kubeconfig.yaml
          echo "UVICORN_PORT=$UVICORN_PORT" >> kubeconfig.yaml
          kubectl apply -f KubernetesManifest.yml

