name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t fastapi .
      - name: Save Docker image
        run: docker save fastapi | gzip > fastapi.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: fastapi
          path: fastapi.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: fastapi
      - name: Load Docker image
        run: docker load < fastapi.tar.gz
      - name: Install dependencies
        run: pip install py3.test
      - name: Run tests
        run: pytest tests

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: fastapi
      - name: Load Docker image
        run: docker load < fastapi.tar.gz
