name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t fastapi .
      - name: Push image to registry
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rockodilu/fastapi:latest

  deploy:
    needs: build
    runs-on: kubernetes-worker
    steps:
      - uses: aws/k8s-action@v3
        with:
          cluster_name: my-cluster
          use_internal_ip: false
          service_account: ingress-service.yaml  # Replace with your service account
      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment.yaml -f ingress-service.yam  # Replace with your manifests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install poetry
      - name: Install project dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
